#!/usr/bin/env bash
#
# awsctx is a utility to manage different aws credentials between several accounts securely
#
# Copyright 2020 Kaden Barlow.
#
# MIT License

# Copyright (c) 2020 kadenbarlow

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

SELF_CMD="$0"
AESCRYPT_PASS=""

change_password() {
  decrypt_data
  printf "Enter New Password: "
  read -s AESCRYPT_PASS
  echo ""
  encrypt_data
}

check_awsctx_json_files() {
  mkdir -p ~/.aws
  if [ ! -f ~/.aws/awsctx.json ]; then
    echo "{\"contexts\": []}" > ~/.aws/awsctx.json
  fi

  if [ ! -f ~/.aws/awsctx-encrypted.json.aes ]; then
    echo "{}" > ~/.aws/awsctx-encrypted.json
    echo "Creating a new encrypted file to store aws credentials... You will be prompted to create a password."
    encrypt_data
  fi
}

check_dependencies() {
  dependencies=(jq aescrypt)
  for dependency in "${dependencies[@]}"; do
    if ! command -v $dependency >/dev/null 2>&1; then
      exit_err "please install $dependency"
    fi
  done
}

choose_context_interactive() {
  local choice
  choice="$(FZF_DEFAULT_COMMAND="${SELF_CMD}" fzf --ansi --no-preview || true)"
  if [[ -z "${choice}" ]]; then
    echo 2>&1 "error: you did not choose any of the options"
    exit 1
  else
    if [[ "$1" == "-s" ]]; then
      set_context "${choice}"
    else
      export_variables "${choice}"
    fi
  fi
}

current_context() {
  jq '.current_context' ~/.aws/awsctx.json -r
}

decrypt_data() {
  get_password
  aescrypt -d -p $AESCRYPT_PASS ~/.aws/awsctx-encrypted.json.aes
  if [ $? -ne 0 ]; then
    exit 1
  fi
}

delete_context() {
  local ctx
  ctx="${1}"
  if [[ "${ctx}" == "." ]]; then
    ctx="$(current_context)" || exit_err "error getting current context"
  fi
  echo "Deleting context \"${ctx}\"..." >&2
  tmp=$(mktemp)
  jq ".contexts = .contexts - [\"${ctx}\"]" ~/.aws/awsctx.json > "$tmp" && mv "$tmp" ~/.aws/awsctx.json

  decrypt_data
  jq "del(.\"${ctx}\")" ~/.aws/awsctx-encrypted.json > "$tmp" && mv "$tmp" ~/.aws/awsctx-encrypted.json
  encrypt_data
}

delete_contexts() {
  for i in "${@}"; do
    delete_context "${i}"
  done
}

encrypt_data() {
  get_password
  aescrypt -e -p $AESCRYPT_PASS ~/.aws/awsctx-encrypted.json
  rm ~/.aws/awsctx-encrypted.json
}

exit_err() {
  echo >&2 "${1}"
  exit 1
}

export_variables() {
  local access_key_id secret_access_key context
  local context="$1"
  if [ -z $context ]; then
    context=$(current_context)
  fi

  decrypt_data
  access_key_id=$(jq ".$context.access_key_id" ~/.aws/awsctx-encrypted.json -r )
  secret_access_key=$(jq ".$context.secret_access_key" ~/.aws/awsctx-encrypted.json -r)
  encrypt_data

  export AWS_ACCESS_KEY_ID="$access_key_id"
  export AWS_SECRET_ACCESS_KEY="$secret_access_key"
}

get_contexts() {
  jq '.contexts[]' ~/.aws/awsctx.json | sed -e 's/"//g'
}

get_password() {
  if [ -z $AESCRYPT_PASS ]; then
    printf "Awsctx Encryption Password: "
    read -s AESCRYPT_PASS
    echo ""
  fi
}

list_contexts() {
  set -u pipefail
  local cur ctx_list
  cur="$(current_context)" || exit_err "error getting current context"
  ctx_list=$(get_contexts) || exit_err "error getting context list"

  local yellow darkbg normal
  highlight=$(tput setaf 118 || true)
  normal=$(tput sgr0 || true)

  for c in $ctx_list; do
    if [[ -z "${NO_COLOR:-}" ]]; then
      # colored output mode
      if [[ "${c}" = "${cur}" ]]; then
        echo "${normal}${highlight}${c}${normal}"
      else
        echo "${c}"
      fi
    else
      echo "here"
      echo "${c}"
    fi
  done
}

new_context() {
  read -p 'Context Name: ' context
  read -p 'AWS Access Key ID: ' access_key_id
  read -p 'Aws Secret Access Key: ' secret_access_key

  decrypt_data

  tmp=$(mktemp)
  jq ".contexts = .contexts + [\"$context\"]" ~/.aws/awsctx.json > "$tmp" && mv "$tmp" ~/.aws/awsctx.json
  jq ".$context = {\"access_key_id\": \"$access_key_id\", \"secret_access_key\": \"$secret_access_key\"}" ~/.aws/awsctx-encrypted.json > "$tmp" \
    && mv "$tmp" ~/.aws/awsctx-encrypted.json

  encrypt_data
  echo "Created context \"${context}\"..." >&2
}

previous_context() {
  jq '.previous_context' ~/.aws/awsctx.json -r
}

rename_context() {
  local old_name="${1}"
  local new_name="${2}"

  if [[ "${old_name}" == "." || "${old_name}" = "$(current_context)" ]]; then
    old_name="$(current_context)"
    save_context $new_name
  fi

  tmp=$(mktemp)
  jq ".contexts.$new_name = .contexts.$old_name | del(.contexts.$old_name)" ~/.aws/awsctx.json > "$tmp" \
    && mv "$tmp" ~/.aws/awsctx.json
}

save_context() {
  tmp=$(mktemp)
  jq ".current_context = \"$1\"" ~/.aws/awsctx.json > "$tmp" && mv "$tmp" ~/.aws/awsctx.json
}

save_previous_context() {
  tmp=$(mktemp)
  jq ".previous_context = \"$1\"" ~/.aws/awsctx.json > "$tmp" && mv "$tmp" ~/.aws/awsctx.json
}

set_context() {
  local prev
  prev="$(current_context)" || exit_err "error getting current context"

  switch_context "${1}"

  if [[ "${prev}" != "${1}" ]]; then
    save_context "${1}"
    save_previous_context "${prev}"
  fi
}

swap_context() {
  local previous
  previous="$(previous_context)"
  set_context $previous
}

switch_context() {
  local access_key_id secret_access_key
  decrypt_data
  access_key_id=$(jq ".$1.access_key_id" ~/.aws/awsctx-encrypted.json -r )
  secret_access_key=$(jq ".$1.secret_access_key" ~/.aws/awsctx-encrypted.json -r)
  encrypt_data

  cat <<EOF > ~/.aws/credentials
[default]
aws_access_key_id = ${access_key_id}
aws_secret_access_key = ${secret_access_key}
EOF

}

usage() {
  local SELF
  SELF="awsctx"

  cat <<EOF
USAGE:
  $SELF                       : list the contexts
  $SELF <NAME>                : switch to context <NAME>
  $SELF -                     : switch to the previous context
  $SELF -e, --export <NAME>   : export context as env, e.g. source awsctx -e <name>
  $SELF -c, --current         : show the current context name
  $SELF -s, --set <NAME>      : fill ~/.aws/credentials with context variables
  $SELF -n, --new             : create a new aws context
  $SELF -p, --password        : change encryption password
  $SELF <NEW_NAME>=<NAME>     : rename context <NAME> to <NEW_NAME>
  $SELF <NEW_NAME>=.          : rename current_context to <NEW_NAME>
  $SELF -d <NAME> [<NAME...>] : delete context <NAME> ('.' for current_context)
                                  (this command won't delete the credentials in ~/.aws/credentials)
  $SELF -h,--help             : show this message
EOF
}

main() {
  check_dependencies
  check_awsctx_json_files

  if [[ "$#" -eq 0 ]]; then
    list_contexts
  elif [[ "${1}" == "-d" ]]; then
    if [[ "$#" -lt 2 ]]; then
      echo "error: missing context NAME" >&2
      usage
      exit 1
    fi
    delete_contexts "${@:2}"
  elif [[ "${1}" == "-e" ]] || [[ "${1}" == "--export" ]]; then
    if [[ "$#" -lt 2 ]]; then
      if [[ -t 1 && -z "${IGNORE_FZF:-}" && "$(type fzf &>/dev/null; echo $?)" -eq 0 ]]; then
        choose_context_interactive "$1"
      else
        usage
        exit 1
      fi
    else
      export_variables "$2"
    fi
  elif [[ "${1}" == "-s" ]] || [[ "${1}" == "--set" ]]; then
    if [[ "$#" -lt 2 ]]; then
      if [[ -t 1 && -z "${IGNORE_FZF:-}" && "$(type fzf &>/dev/null; echo $?)" -eq 0 ]]; then
        choose_context_interactive "$1"
      else
        usage
        exit 1
      fi
    else
      set_context "$2"
    fi
  elif [[ "$#" -gt 1 ]]; then
    echo "error: too many arguments" >&2
    usage
    exit 1
  elif [[ "$#" -eq 1 ]]; then
    if [[ "${1}" == "-" ]]; then
      swap_context
    elif [[ "${1}" == '-c' || "${1}" == '--current' ]]; then
      current_context
    elif [[ "${1}" == '-n' || "${1}" == '--new' ]]; then
      new_context
    elif [[ "${1}" == '-p' || "${1}" == '--password' ]]; then
      change_password
    elif [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
      usage
    elif [[ "${1}" =~ ^-(.*) ]]; then
      echo "error: unrecognized flag \"${1}\"" >&2
      usage
      exit 1
    elif [[ "${1}" =~ (.+)=(.+) ]]; then
      rename_context "${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
    else
      set_context "${1}"
    fi
  else
    usage
    exit 1
  fi
}

main "$@"
